name: qpt_compact
description: A cli app for compress and decompress files and folders.
version: 1.1.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  archive: ^3.1.2
  colorize: ^3.0.0
  args: ^2.2.0